<style>

body{
    min-height: 100vh!important; /* will cover the 100% of viewport */
    display: block !important;
    position: relative !important;
    padding-bottom: 120px !important;
}

footer{
    height: 120px !important;
  	background-size: cover !important;
    /* Para ficar sempre no bottom */
    position:absolute !important;
    bottom:0 !important;
    width: 100% !important;
}

</style>

    <footer class="footer">
        <div class="content has-text-centered">
            <p>
              Desenvolvido por <a class="tooltip is-tooltip-info" data-tooltip="nunesbernardo2000@gmail.com">Bernardo Nunes</a>,
              <a class="tooltip is-tooltip-info" data-tooltip="bryans0701@gmail.com">Bryan Santos</a> e
              <a class="tooltip is-tooltip-info" data-tooltip="willian.va7@gmail.com">Willian Vítor</a>
            </p>
        </div>
    </footer>
