
    <footer class="my-footer">
        <div class="content has-text-centered">
            <p>
              Desenvolvido por <a class="tooltip is-tooltip-link" data-tooltip="nunesbernardo2000@gmail.com">Bernardo Nunes</a>,
              <a class="tooltip is-tooltip-link" data-tooltip="bryans0701@gmail.com">Bryan Santos</a> e
              <a class="tooltip is-tooltip-link" data-tooltip="willianv1tor.dev@gmail.com">Willian Vitor</a>
            </p>
        </div>
    </footer>
