<nav class="navbar is-dark" role="navigation" aria-label="main navigation">
        <div class="navbar-brand">
            <a class="navbar-item" href="index.php">
                <img src="Images/logo.png">
            </a>

            <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="navbar">
                <span aria-hidden="true"></span>
                <span aria-hidden="true"></span>
                <span aria-hidden="true"></span>
            </a>
        </div>

            <div id="navbar" class="navbar-menu">
                <div class="navbar-start">
                    <a class="navbar-item" href="index.php">
                      Home
                    </a>
                    <a class="navbar-item is-hoverable" href="reservar.php">
                        Reservas
                    </a>
                    <a class="navbar-item is-hoverable">
                        Espaços
                    </a>
                </div>

                <div class="navbar-end">
                    <div class="navbar-item">
                      <div class="field is-grouped">
                        <p class="control">
                          <button class="button is-success">
                            <span class="icon">
                              <i class="fas fa-user"></i>
                            </span>
                            <span>
                              Login
                            </span>
                          </button>
                          <button class="button">
                            <span class="icon">
                              <i class="fas fa-user"></i>
                            </span>
                            <span>
                              Cadastro
                            </span>
                          </button>
                        </p>
                      </div>
                    </div>
                </div>
            </div>
        </nav>

        <section class="section has-background-dark" style="padding-bottom: 70px !important">
            <div class="container">
                <h1 class="title has-text-centered has-text-white"> Reservas COLTEC</h1>
                <h2 class="subtitle has-text-centered has-text-light"> Para reservar a sala ou espaço que você precisa no Colégio!</h2>
            </div>
        </section>
