<nav class="navbar" role="navigation" aria-label="main navigation">
        <div class="navbar-brand">
            <a class="navbar-item" href="index.html">
                <img src="http://www.ufmg.br/online/marketing/arquivos/anexos/coltec_logo_proposta1.jpg" alt="Bulma: a modern CSS framework based on Flexbox" width="112" height="28">
            </a>

            <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="navbar">
                <span aria-hidden="true"></span>
                <span aria-hidden="true"></span>
                <span aria-hidden="true"></span>
            </a>
        </div>
              
            <div id="navbar" class="navbar-menu">
                <div class="navbar-start">
                    <a class="navbar-item" href="index.html">
                      Home
                    </a>
                    <a class="navbar-item is-hoverable">
                        Reservas
                    </a>
                    <a class="navbar-item is-hoverable">
                        Espaços
                    </a>
                </div>
              
                <div class="navbar-end">
                    <div class="navbar-item">
                      <div class="field is-grouped">
                        <p class="control">
                          <a class="bd-tw-button button" data-social-network="Twitter" data-social-action="tweet" data-social-target="http://localhost:4000" target="_blank" href="https://twitter.com/intent/tweet?text=Bulma: a modern CSS framework based on Flexbox&amp;hashtags=bulmaio&amp;url=http://localhost:4000&amp;via=jgthms">
                            <span class="icon">
                              <i class="fas fa-user"></i>
                            </span>
                            <span>
                              Login
                            </span>
                          </a>
                        </p>
                      </div>
                    </div>
                </div>
            </div>
        </nav>